### ISSUE TITLE
Timer.cpp

### ISSUE THREAD

**Issue by Annoraaq** [untergam/DHPC_TopoSort#5]
I wanted to put the methods of the Timer class into the timer.cpp but that did not work. I always get a "not defined reference" error at compile time. Could someone try to do this? The methods should not be in the header class. This was just a workaround.

**Comment by walkevin** [comment]
I played around with some timers. It seems that the current clock is not so reliable, at least it never gives any speedup. I read somewhere that it adds up the times from all threads.

The most reliable timer seems to be the rdtsc-timer and the std::chrono timer. At least I get an expected speedup for a trivially parallelizable task. The timers are nicely included in `rdtsc_timer.hpp` (see e69bba4) , a class that I got from the Programming Techniques II course.

The experiment that I carried out is at this link.
https://gist.github.com/walkevin/3c49807351dd6bf6766f

The results are

Threads: 1
timer_clock [s]:    0.011571
timer_gettimeofday [s]: 0.00658
timer_omp [s]:  0.00762846
timer_rdtsc, chrono [s]:    0.00980848
timer_rdtsc, cycles [cycles]:   2.64205e+07

Threads: 8 (8 Threads with hyper-threading, there are only 4 processors)
timer_clock [s]:    0.013722
timer_gettimeofday [s]: 0.001724
timer_omp [s]:  0.00172499
timer_rdtsc, chrono [s]:    0.00191066
timer_rdtsc, cycles [cycles]:   5.14639e+06
